# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-29 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentIds', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('studentName', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
