# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-16 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campus_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('facultyId', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('facultyName', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='elective',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='courses',
            name='offered_In',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campus_admin.Semester'),
        ),
        migrations.AddField(
            model_name='courses',
            name='offered_to',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('IT', 'Information Technology'), ('CS&IT', 'Computer Science and Information Technology')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campus_admin.Faculty'),
        ),
    ]
