# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-29 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acadYears', models.CharField(default='', max_length=10)),
                ('semesterNos', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together=set([('acadYears', 'semesterNos')]),
        ),
    ]
