# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-29 03:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campus_admin', '0002_auto_20171029_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acadYear', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acadYear+', to='campus_admin.Semester')),
                ('semesterNo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semesterNo+', to='campus_admin.Semester')),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus_admin.Student')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='registers',
            unique_together=set([('studentId', 'acadYear', 'semesterNo')]),
        ),
    ]
