# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-29 03:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campus_admin', '0004_auto_20171029_0850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semester',
            old_name='acadYears',
            new_name='acadYear',
        ),
        migrations.RenameField(
            model_name='semester',
            old_name='semesterNos',
            new_name='semesterNo',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='studentIds',
            new_name='studentId',
        ),
        migrations.AlterField(
            model_name='registers',
            name='studentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentId+', to='campus_admin.Student'),
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together=set([('acadYear', 'semesterNo')]),
        ),
    ]
