# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-29 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_admin', '0005_auto_20171029_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.CharField(default='', max_length=10),
        ),
    ]
