# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-29 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_admin', '0006_student_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.IntegerField(default='', max_length=10),
        ),
    ]
