# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-31 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campus_admin', '0009_auto_20171029_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('courseNo', models.CharField(default='', max_length=10, primary_key=True, serialize=False)),
                ('courseName', models.CharField(default='', max_length=100)),
                ('credits', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='semester',
            name='semesterNo',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='registers',
            name='courseNo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='courseNo+', to='campus_admin.Courses'),
        ),
        migrations.AlterUniqueTogether(
            name='registers',
            unique_together=set([('studentId', 'acadYear', 'semesterNo', 'courseNo')]),
        ),
    ]
