# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-31 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campus_admin', '0010_auto_20171031_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SPI', models.FloatField(default='')),
                ('acadYear', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acadYear+', to='campus_admin.Semester')),
                ('semesterNo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semesterNo+', to='campus_admin.Semester')),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentId+', to='campus_admin.Student')),
            ],
        ),
        migrations.AddField(
            model_name='registers',
            name='grade',
            field=models.CharField(default='', max_length=5),
        ),
    ]
