# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-31 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_admin', '0014_auto_20171031_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='SPI',
            field=models.FloatField(blank=True, default='', null=True),
        ),
    ]
