# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-31 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_admin', '0021_auto_20171031_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registers',
            name='grade',
            field=models.CharField(default='', max_length=5),
        ),
    ]
