# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-01 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campus_admin', '0024_auto_20171031_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='courseNo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courseNo+', to='campus_admin.Courses'),
        ),
    ]
