# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-01 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campus_admin', '0025_semester_courseno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='courseNo',
        ),
        migrations.AddField(
            model_name='courses',
            name='acadYear',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acadYear+', to='campus_admin.Semester'),
        ),
        migrations.AddField(
            model_name='courses',
            name='semesterNo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semesterNo+', to='campus_admin.Semester'),
        ),
    ]
