# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-01 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus_admin', '0027_auto_20171101_2318'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='offers',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='offers',
            name='acadYear',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='courseNo',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='semesterNo',
        ),
        migrations.DeleteModel(
            name='Offers',
        ),
    ]
