# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-01 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campus_admin', '0029_auto_20171101_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=4, null=True)),
                ('acadYear', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acadYear+', to='campus_admin.Semester')),
                ('courseNo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courseNo+', to='campus_admin.Courses')),
                ('semesterNo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semesterNo+', to='campus_admin.Semester')),
                ('studentId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentId+', to='campus_admin.Student')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='offers',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='offers',
            name='acadYear',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='courseNo',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='semesterNo',
        ),
        migrations.DeleteModel(
            name='Offers',
        ),
        migrations.AlterUniqueTogether(
            name='registers',
            unique_together=set([('acadYear', 'semesterNo', 'courseNo')]),
        ),
    ]
