# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-01 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campus_admin', '0030_auto_20171102_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acadYear', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acadYear+', to='campus_admin.Semester')),
                ('courseNo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courseNo+', to='campus_admin.Courses')),
                ('semesterNo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semesterNo+', to='campus_admin.Semester')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='registers',
            unique_together=set([('acadYear', 'semesterNo', 'courseNo', 'studentId')]),
        ),
        migrations.AlterUniqueTogether(
            name='offers',
            unique_together=set([('acadYear', 'semesterNo', 'courseNo')]),
        ),
    ]
