# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-02 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_admin', '0031_auto_20171102_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.FloatField(default=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentId',
            field=models.FloatField(default=0, primary_key=True, serialize=False),
        ),
    ]
