# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-02 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_admin', '0032_auto_20171102_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentId',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
