# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-02 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_admin', '0033_auto_20171102_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='acadYear',
            field=models.CharField(default='', max_length=20),
        ),
    ]
