# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-02 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_admin', '0034_auto_20171102_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registers',
            name='grade',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
