# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-03 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campus_admin', '0036_auto_20171103_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiptId', models.CharField(max_length=30, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('acadYear', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acadYear+', to='campus_admin.Semester')),
                ('semesterNo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semesterNo+', to='campus_admin.Semester')),
                ('studentId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feereceipt_studentId', to='campus_admin.Student')),
            ],
        ),
    ]
