# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-03 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_admin', '0037_feereceipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feereceipt',
            name='id',
        ),
        migrations.AlterField(
            model_name='feereceipt',
            name='receiptId',
            field=models.CharField(default='', max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='feereceipt',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
