# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-03 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_admin', '0039_auto_20171103_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feereceipt',
            name='status',
            field=models.CharField(blank=True, default='Not Paid', max_length=50),
        ),
    ]
